from vllm.entrypoints.chat_utils import ChatCompletionMessageParam


prompts_dict = {
    "prompt1": """content of prompt 1""",
    "prompt2": """content of prompt 2, with the first {_inp1_} and {_inp2_}"""
}


def return_prompt(prompt_name: str) -> str:
    """
    Fetch a given prompt from the prompts dict. Use this if you have some generic prompt templates to use.

    Args:
        prompt_name: the name of the prompt as it appears in the prompts_dict.

    Returns: the text of the prompt as a string.
    """
    return prompts_dict.get(prompt_name)


def return_prompt_with_blanks(prompt_name: str, args: list[str]) -> str:
    """
    Fetch a given prompt from the prompts dict with additional arguments for filling in blanks.
    Arguments should be passed as a list of strings in the order they'll appear in the prompt's text.

    Args:
        prompt_name: the name of the prompt as it appears in the prompts_dict.
        args: a list of words or phrases to fill in the prompt text.

    Returns: the text of the prompt as a string with blank words filled in.
    """
    kwargs = {f"_inp{idx+1}_": val.strip() for idx, val in enumerate(args)}
    prompt = prompts_dict.get(prompt_name).format(**kwargs)
    return prompt


def apply_chat_template(sys_prompt: str, usr_prompt: str, previous_messages: list[dict[str, str]] = None) -> list[dict[str, str]]:
    """
    Applies the standard list-of-dicts system-user-assistant chat template to the prompts list.

    Args:
        sys_prompt: The system prompt as a string.
        usr_prompt: The user input prompt as a string
        previous_messages: If there's history to maintain, pass this in. The new message will be appended and returned instead.

    Returns: Chat template formatted list of messages.
    """
    if previous_messages:
        return previous_messages + [{"role": "user", "content": usr_prompt}]

    chat_template = [
        {"role": "system", "content": sys_prompt},
        {"role": "user", "content": usr_prompt.replace("  ", " ")},
    ]
    return chat_template


def apply_chat_template_over_list(system_prompt: str, prompts_list: list[str]) -> list[ChatCompletionMessageParam]:
    """
    Applies the apply_chat_template function over a list of user prompts. This function called in the end-to-end flow to
    apply the template to all perturbed variants of a prompt.

    Args:
        system_prompt: The system prompt as a string.
        prompts_list: A list of user prompts generated by the perturbation step.

    Returns: A list of chat templated conversations, each of which are only different in the perturbed user input.
    """
    chats_list = []
    for prompt in prompts_list:
        chats_list.append(apply_chat_template(sys_prompt=system_prompt, usr_prompt=prompt))
    return chats_list


if __name__ == "__main__":
    print(return_prompt(prompt_name="prompt1"))
    print(return_prompt_with_blanks(prompt_name="prompt2", args=["hello", "there"]))